version: "3.9"
services:
  db:
    container_name: soap_mysql
    image: mysql:latest
    hostname: mysql
    ports:
      - "9001:3306"
    restart: always
    healthcheck:
      test: mysqladmin ping -h localhost -u${MYSQL_USER} -p{MYSQL_PASSWORD}
      interval: 5s
      timeout: 5s
      retries: 20
    networks:
      - binotify-soap
    env_file: .env
    volumes:
      - ./mysql:/var/lib/mysql
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql

  binotify_soap:
    container_name: soap
    build: .
    hostname: soap
    env_file:
      - .env
    ports:
      - "9000:9000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - binotify-soap

volumes:
  mysql:
    driver: local

networks:
  binotify-soap: